#!/usr/bin/env python
# -*- coding:UTF-8 -*-
#@Time:2016/11/21 下午6:38
#@Author:grape.lee
#@File:test_cmdb
#@Software:PyCharm Community Edition

import sys
import struct
import hmac
import hashlib
import time
#import requests
import urllib
import argparse
import json
from binascii import hexlify
from collections import namedtuple
from cmdblib.client import Client

reload(sys)
sys.setdefaultencoding('utf8')

def get_cmdb_client():
    client_id = ''
    secret = ''
    host = ''
    port = 8080
    return Client(host=host, port=port, client_id=client_id, secret=secret)

cli=get_cmdb_client()

def get_hosts_by_uanme ():
    rest=cli.search_entities('server_logic',ops_no="E045282李瑞刚",size=99999)
    for i in rest:
        print(i.hostname)
#get_hosts_by_uanme()

def get_ip_by_host(hostname):
    for host in hostname:
        rest = cli.search_entities('server_logic',hostname=host,size=99999)
        for i in rest:
            print(i.nic0_ip[0])

#get_ip_by_host('xg-napos-nevermore-service-1')

def get_host_by_ip(ip):
    for addr in ip.split(','):
        rest = cli.search_entities('server_logic',nic0_ip=addr,size=99999)
        for i in rest:
            print(i.hostname)

#get_host_by_ip('10.0.46.164')

def get_hosts_by_appid(appid):
    for app in appid.split(','):
        print(app)
        rest=cli.search_entities('rl_group_hosts',app_id=app,idc_code='xg',size=99999)
        for i in rest:
            if len(i.hosts)>0:
                for m in range(len(i.hosts)):
                    print(i.hosts[m])
#get_hosts_by_appid('nevermore.service')

def get_appid_by_hostname(hostname):
    for host in hostname.split(','):
        rest=cli.search_entities('rl_group_hosts',hosts=host,idc_code='xg',size=99999)
        for i in rest:
            if 'arch.samaritan' not in i.app_id:
                print(i.app_id)

#get_appid_by_hostname('xg-napos-nevermore-service-2')


'''if __name__ == "__main__":
    search_list=['get_ip_by_host','get_host_by_ip','get_hosts_by_appid','get_appid_by_hostname']
    print(search_list)
    searchd = input('Please input what kind of method you want you select:')
    if searchd:
        things = input('Please input your condition:')
        searchd("%s" % things)'''

def help():
    print('usage: %s ') % \
         ('''
         python get_ip_by_host xg-napos-order-1
         python get_host_by_ip 10.0.52.146,10.0.52.147
         python get_hosts_by_appid nevermore.api,nevermore.service
         python get_appid_by_hostname xg-napos-order-1,xg-napos-nevermore-api-1''')
    sys.exit()


if __name__ == "__main__":
    if len(sys.argv) != 3:
        help()
    operation = sys.argv[1]
    arguments = sys.argv[2]
    if operation == 'get_ip_by_host':
        get_ip_by_host(arguments)
    elif operation == 'get_host_by_ip':
        get_host_by_ip(arguments)
    elif operation == 'get_hosts_by_appid':
        get_hosts_by_appid(arguments)
    elif operation == 'get_appid_by_hostname':
        get_appid_by_hostname(arguments)







